### ISSUE TITLE
Call to /_replicate hangs using the couchbase-lite-local.jar and Sync Gateway

### ISSUE THREAD

**Issue by dvdgllnt** [couchbaselabs/couchbase-lite-local#10]
I have Sync Gateway running on one of my servers. I have couchbase lite local running on a client machine running Ubuntu 12 with JDK 8: `java -jar couchbase-lite-local.jar`

I can post/get documents from CBL using the REST API. However, when I send a POST to `/_replicate`, the rest client hangs and does not get a response back from the server.

To rule out the sync gateway, I spun up a CouchDB database and called `/_replicate` and it replicates to the Sync Gateway without issue.

``` python
# using Python requests module
import requests

# substituted my real IP with x.x.x.x, my test database is called pizza
# sync gateway has GUEST access enabled. I also tried :4985 (admin port) and it still hangs
doc = {'source' : 'pizza', 'target' : 'http://x.x.x.x:4984/sync_gateway'}

heads =  {'Content-Type': 'application/json'}

resp = requests.post('http://localhost:5984/_replicate', data=json.dumps(doc), headers=heads, auth=('2974f70d-a653-4d9a-9e28-bc2b622ce0cf', '3525695d-a95b-497d-9c95-a33f57348c86'))

#hangs
```

**Comment by sideshowcoder** [comment]
I wonder if there might be a bug in the java version which couchbase-lite-local is bound to, it there might have been a newer release since I bundled those dependencies in. @tleyden I see you guys are working towards unit tests on couchbase/couchbase-lite-android#515 @hideki anything like this known?

**Comment by hideki** [comment]
Hi @vzdavid and @sideshowcoder 

Could you please give us more information? we might be able to help you.

We usually need information which is described in following page. 
https://github.com/couchbase/couchbase-lite-java-core/blob/master/CONTRIBUTING.md

**Comment by dvdgllnt** [comment]
I'm using Java(TM) SE Runtime Environment (build 1.8.0_31-b13) from Oracle (not openjdk) on Ubuntu 12.04. I'm using the latest couchbase-lite-local.jar (v1.0.3) from the releases link in github (https://github.com/couchbaselabs/couchbase-lite-local/releases). Using an extremely simple example of posting a document, then a POST to `/_replicate`. It hangs with no response from TJWS on the replicate call. Note: I am not using Android, just a pure Linux distro.

**Comment by hideki** [comment]
@vzdavid Can you see any log message at Sync Gateway side? request log or response log?

@sideshowcoder I am not familiar with couchbase-lite-local, can you investigate little further? If this is couchbase-lite-java issue, please file the ticket against https://github.com/couchbase/couchbase-lite-java ?

**Comment by dvdgllnt** [comment]
I'm watching the logs, nothing happens when I call _replicate from CBL local, so I'm guessing it's not hitting the gateway.

```
21:35:33.475937 ==== Couchbase Sync Gateway/1.0.3(81;fa9a6e7) ====
21:35:33.476958 Configured Go to use all 4 CPUs; setenv GOMAXPROCS to override this
21:35:33.477027 Opening db /sync_gateway as bucket "sync_gateway", pool "default", server <http://x.x.x.x:8091>
21:35:33.477148 Opening Couchbase database sync_gateway on <http://x.x.x.x:8091>
21:35:33.618603 Using default sync function 'channel(doc.channels)' for database "sync_gateway"
21:35:33.618631 Starting profile server on
21:35:33.618646 Starting admin server on x.x.x.x:4985
21:35:33.622700 Starting server on :4984 ...
```

**Comment by dvdgllnt** [comment]
However, if I spin up Apache CouchDB, and try the same _replicate, it works. I can see the following on sync gateway:

```
21:45:47.761373 HTTP:  #001: HEAD /sync_gateway/  (ADMIN)
21:45:47.766288 HTTP:  #002: GET /sync_gateway/  (ADMIN)
21:45:47.772687 HTTP:  #003: GET /sync_gateway/_local/16b6f6d5b0c77d470152836328db528d  (ADMIN)
```

**Comment by hideki** [comment]
Hi @vzdavid 

Is it possible to enable logging at CBL side? Ideally INFO or DEBUG level?

**Comment by atom992** [comment]
Hi I am using
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
on MAC OS X Yosemite version 10.10.2
with same problem -- I can post/get documents from CBL using the REST API. However, when I send a POST to /_replicate, the rest client hangs and does not get a response back from the server.

**Comment by ijokarumawak** [comment]
Hi @hideki 

I'm running into the same issue.
Captured Java thread dump while it gets hang:
https://gist.github.com/ijokarumawak/8e9a49aaf8a0bcb7a7bc

It seems that Router is waiting for the replicator's Replication.ChangeListener to be called, but it's never get called.

```
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
at com.couchbase.lite.router.Router.do_POST_replicate(Router.java:649)
```

**Comment by hideki** [comment]
Hi @ijokarumawak

Thank you very much for additional information.
It seems there is an issue in Replicator state.

Current version of couchbase-lite-local contains CBL Java 1.0.3.
After v1.0.3, we added many bug fixes into master branch.
Please try CBL Java master branch version? 
You can download from http://mobile.jenkins.couchbase.com/job/couchbase-lite-java-create-zip/70/ .

Please let us know if upgrading to latest build from master branch solves this issue.

Thanks!

**Comment by ijokarumawak** [comment]
@hideki 

Thanks for your quick reply.
For the short answer, it works if I use the latest couchbase-lite-java!

I tried to build couchbase-lite-local project myself, so that I can upgrade dependencies.
But since I'm not a Ruby guy, I couldn't solve the error thrown with _bundle install_ :

```
bundle install
Fetching gem metadata from https://rubygems.org/...
Fetching version metadata from https://rubygems.org/..
Could not find gem 'couchbase_lite_local (>= 0) java' in source at ..
Source contains 'couchbase_lite_local' at: 0.0.4
```

So, I did:
1. Download the latest [couchbase-lite-java](http://mobile.jenkins.couchbase.com/job/couchbase-lite-java-create-zip/70/) and unpack it
2. unpack **couchbase-lite-local.jar**
3. put the step-1's couchbase-lite-java-0.0.0-512/\* to step-2's **_couchbase-lite-local/vendor**_ dir
4. create couchbase-lite-local.jar again

I hope I could send a pull request to update depending couchbase-lite version, but I don't know the appropriate way...

Thanks!

**Comment by hideki** [comment]
Hi @ijokarumawak Thank you for sharing test result!!

**Comment by sideshowcoder** [comment]
I created a new jar, [with the fix](https://github.com/couchbaselabs/couchbase-lite-local/releases/tag/v0.0.5-pre) could you try it out? It seems to work, but I want to confirm.

**Comment by atom992** [comment]
Hi,I using:
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
on MAC OS X Yosemite version 10.10.2
with the following jar:
https://github.com/couchbaselabs/couchbase-lite-local/releases/download/v0.0.5-pre/couchbase-lite-local.jar
to call to /_replicate ,get the following errors on console:
May 14, 2015 11:14:35 PM com.couchbase.lite.util.SystemLogger w
WARNING: Router: WARNING: Exception parsing body into dictionary
org.codehaus.jackson.JsonParseException: Unexpected character ('c' (code 99)): was expecting double-quote to start field name
 at [Source: Acme.Serve.Serve$ServeInputStream@4f40a556; line: 1, column: 155]
    at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
    at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
    at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
    at org.codehaus.jackson.impl.Utf8StreamParser._handleUnusualFieldName(Utf8StreamParser.java:1531)
    at org.codehaus.jackson.impl.Utf8StreamParser._parseFieldName(Utf8StreamParser.java:1221)
    at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:489)
    at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:304)
    at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249)
    at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
    at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900)
    at com.couchbase.lite.router.Router.getBodyAsDictionary(Router.java:168)
    at com.couchbase.lite.router.Router.do_POST_replicate(Router.java:617)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.couchbase.lite.router.Router.start(Router.java:466)
    at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
    at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
    at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
    at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
    at java.lang.Thread.run(Thread.java:745)

**Comment by sideshowcoder** [comment]
What does the request look like you are sending? It seems to error on the JSON so I can probably create a test for it to see what is going on.

**Comment by atom992** [comment]
curl -X POST -H "Content-Type:application/json" http://0317e308-537c-420c-b408-934cc6a42032:12da0346-c647-425b-bbd3-242a26bc62e3@localhost:5984/_replicate --data '{"source": {"headers": {"Cookie":"SyncGatewaySession=4b6c7ae39457c657f8d5fdcf7a75613190a0df32"},"url":"http://_._._._/todos/"},"target" : "todos",continuous : true}'

**Comment by atom992** [comment]
If I use following command:
curl -X POST -H "Content-Type:application/json" http://0317e308-537c-420c-b408-934cc6a42032:12da0346-c647-425b-bbd3-242a26bc62e3@localhost:5984/_replicate --data '{"source": {"headers": {"Cookie":"SyncGatewaySession=4b6c7ae39457c657f8d5fdcf7a75613190a0df32"},"url":"http://.../todos/"},"target" : "todos"}'

I got no response.

**Comment by yonahforst** [comment]
same here. using the v0.0.5-pre, calls to _replicate still hang.

I tried building it like @ijokarumawak suggested but couldn't get it back into a jar (not a java guy).

@sideshowcoder  any other suggestions?
